### ISSUE TITLE
Help!! Device tree for lyf f1 LS-5505

### ISSUE THREAD

**Issue by ghost** [dotOS-Devices/android_device_LYF_mobee01a#1]
I am trying to build a custom a rom for LYF LS-5505 aka lyf f1. But cannot found any device tree available. Can anyone guide me how to build a device tree from scratch. I have boot.img, recovery.img, /system/vendor, system.prop, build.prop files with me but how to build device tree?

**Comment by AndroiableDroid** [comment]
find a device with similar specs and follow it
